import os
from collections import OrderedDict
import numpy as np
import h5py

__all__ = [
	'print_info',
	'print_scope_channels',
	'read_positions',
	'map_structure_to_text',
]

#===============================================================================================================================================
#=============read hdf5 generated by Python LAPD_DAQ===========================================================
#===============================================================================================================================================
def _decode_hdf5_value(value):
	"""Return HDF5 attribute values as ordinary Python objects."""
	if isinstance(value, bytes):
		return value.decode('utf-8', errors='replace')
	if isinstance(value, np.bytes_):
		return value.decode('utf-8', errors='replace')
	if isinstance(value, np.ndarray):
		if value.shape == ():
			return _decode_hdf5_value(value[()])
		return [_decode_hdf5_value(item) for item in value.tolist()]
	if isinstance(value, np.generic):
		return value.item()
	if isinstance(value, (list, tuple)):
		return [_decode_hdf5_value(item) for item in value]
	return value

def _hdf5_value_to_text(value):
	value = _decode_hdf5_value(value)
	if isinstance(value, list):
		if all(isinstance(item, str) for item in value):
			return '\n'.join(value)
		return str(value)
	return str(value)

def _find_description_attribute(attrs):
	for attr_name in attrs:
		if attr_name.lower() == 'description':
			return attr_name, _hdf5_value_to_text(attrs[attr_name])
	return None, None

def _is_section_underline(line):
	line = line.strip()
	return len(line) >= 3 and set(line) <= {'=', '-', '_'}

def _clean_section_title(line):
	return line.strip().strip('#').strip().rstrip(':').strip()

def _canonical_description_section(title):
	title_lower = title.lower().replace('.', '')

	if 'b field' in title_lower or 'magnetic' in title_lower or 'magnet' in title_lower:
		return 'Magnetic field'
	if 'timing' in title_lower or title_lower in {'trigger', 'triggers'}:
		return 'Timing'
	if (
		'plasma setting' in title_lower
		or 'plasma condition' in title_lower
		or title_lower in {'plasma', 'discharge', 'discharge setting', 'gas', 'gas setting'}
	):
		return 'Plasma setting'
	if 'scope' in title_lower or 'channel' in title_lower or 'digitizer' in title_lower or 'diagnostic' in title_lower:
		return 'Diagnostics'
	if 'probe' in title_lower or 'motion' in title_lower or 'position' in title_lower:
		return 'Probe/motion'
	if 'bias' in title_lower or 'electrode' in title_lower or 'sweep' in title_lower:
		return 'Biasing'
	if 'run description' in title_lower:
		return 'Run description'
	if 'exp' in title_lower and 'description' in title_lower:
		return 'Experiment description'
	return title

def _trim_blank_lines(lines):
	lines = list(lines)
	while lines and not lines[0]:
		lines.pop(0)
	while lines and not lines[-1]:
		lines.pop()
	return lines

def _split_description_sections(description):
	sections = OrderedDict()
	current_section = None
	lines = description.splitlines()
	i = 0

	while i < len(lines):
		line = lines[i].rstrip()
		stripped = line.strip()

		if _is_section_underline(stripped):
			i += 1
			continue

		next_line = lines[i + 1].strip() if i + 1 < len(lines) else ''
		is_underlined_heading = stripped and _is_section_underline(next_line)
		is_colon_heading = stripped.endswith(':') and len(stripped) <= 80

		if is_underlined_heading or is_colon_heading:
			section_title = _clean_section_title(stripped)
			current_section = _canonical_description_section(section_title)
			sections.setdefault(current_section, [])
			if is_underlined_heading:
				i += 2
			else:
				i += 1
			continue

		if current_section is None:
			current_section = 'Other'
			sections.setdefault(current_section, [])

		if stripped:
			sections[current_section].append(stripped)
		elif sections[current_section] and sections[current_section][-1]:
			sections[current_section].append('')

		i += 1

	for section_name in list(sections.keys()):
		sections[section_name] = _trim_blank_lines(sections[section_name])
		if not sections[section_name]:
			del sections[section_name]

	return sections

def print_info(ifn):
	with h5py.File(ifn, 'r') as f:
		description_attr, description = _find_description_attribute(f.attrs)

		print("HDF5 file information")
		print("=====================")

		attributes = [(key, value) for key, value in f.attrs.items() if key != description_attr]
		if attributes:
			print("\nFile attributes:")
			for key, value in attributes:
				print(f"  {key}: {_hdf5_value_to_text(value)}")

		print("\nData description:")
		if description:
			for section_name, section_lines in _split_description_sections(description).items():
				print(f"\n{section_name}")
				print("-" * len(section_name))
				for line in section_lines:
					if line:
						print(f"  {line}")
					else:
						print()
		else:
			print("  No description attribute found.")

		print("\nGroups in file:")
		for group in f.keys():
			print(f"  {group}")

def print_scope_channels(hdf5_filename, scope_name):
	"""
	Print all channel descriptions from a selected scope group in an HDF5 file.

	Parameters:
	-----------
	hdf5_filename : str
		Path to the HDF5 file
	scope_name : str
		Name of the scope group to examine (e.g., 'xrayscope', 'magscope')

	Returns:
	--------
	None
	"""
	with h5py.File(hdf5_filename, 'r') as f:
		# Check if scope exists
		if scope_name not in f:
			print(f"Scope '{scope_name}' not found in file.")
			return

		scope_group = f[scope_name]
		print(f"\n=== Channel Descriptions for {scope_name} ===")

		# Find the first shot group to get channel information
		shot_groups = [k for k in scope_group.keys() if k.startswith('shot_')]
		if not shot_groups:
			print("No shot data found in this scope group.")
			return

		# Use the first non-skipped shot
		shot_group = None
		for shot_name in shot_groups:
			current_shot = scope_group[shot_name]
			# Skip shots that were marked as skipped
			if 'skipped' in current_shot.attrs and current_shot.attrs['skipped']:
				continue
			shot_group = current_shot
			break

		if shot_group is None:
			print("All shots were skipped in this scope group.")
			return

		# Extract channel names and their descriptions
		channel_names = [k.split('_')[0] for k in shot_group.keys() if k.endswith('_data')]

		# Print channel information
		for channel in sorted(channel_names):
			data_key = f"{channel}_data"
			if data_key in shot_group:
				if 'description' in shot_group[data_key].attrs:
					desc = shot_group[data_key].attrs['description']
					print(f"  {channel}: {desc}")
				else:
					print(f"  {channel}: No description available")

def read_positions(hdf5_filename, motion_group_name=None):
	"""
	Read Control/Positions data from HDF5 file written by acquisition_bmotion.py

	Parameters:
	-----------
	hdf5_filename : str
		Path to the HDF5 file
	motion_group_name : str, optional
		Name of the motion group to read. If None, will list available groups
		and use the first one if only one exists.

	Returns:
	--------
	pos_array : ndarray
		Full position array (structured array with fields shot_num, x, y)
	npos : int
		Number of unique positions
	nshot : int
		Number of shots per position
	"""
	with h5py.File(hdf5_filename, 'r') as f:
		if 'Control/Positions' not in f:
			print("No Control/Positions group found in file.")
			return None

		positions_group = f['Control/Positions']

		# List available motion groups
		mg_list = list(positions_group.keys())
		if len(mg_list) == 0:
			print("No motion groups found in Control/Positions.")
			return None

		print(f"Available motion groups: {mg_list}")

		if motion_group_name is None:
			if len(mg_list) == 1:
				motion_group_name = mg_list[0]
				print(f"Using motion group: {motion_group_name}")
			else:
				print("Multiple motion groups found. Please specify motion_group_name")
				return None

		if motion_group_name not in positions_group:
			print(f"Motion group '{motion_group_name}' not found.")
			return None

		mg_group = positions_group[motion_group_name]

		if 'positions_array' not in mg_group:
			print(f"positions_array not found in {motion_group_name}.")
			return None

		pos_array = mg_group['positions_array'][:]

		print(f"Position array shape: {pos_array.shape}")
		print(f"Position array dtype: {pos_array.dtype}")
		print(f"Structured array fields: {pos_array.dtype.names}")

		# Get motion_list which contains the planned unique positions
		if 'motion_list' not in mg_group:
			print(f"motion_list not found in {motion_group_name}.")
			return None

		motion_list = mg_group['motion_list'][:]
		npos = len(motion_list)

		# Find number of shots per position by counting consecutive identical (x, y) pairs
		# from the start of positions_array. All shots at the same position are contiguous.
		x0_rounded = np.round(pos_array['x'][0], 2)
		y0_rounded = np.round(pos_array['y'][0], 2)

		nshot = 0
		for i in range(len(pos_array)):
			x_rounded = np.round(pos_array['x'][i], 2)
			y_rounded = np.round(pos_array['y'][i], 2)
			if x_rounded == x0_rounded and y_rounded == y0_rounded:
				nshot += 1
			else:
				break

		print(f"Number of shots: {len(pos_array)}")
		print(f"Shots per position: {nshot}")
		print(f"Number of unique positions: {npos}")


		return motion_list, pos_array, npos, nshot


#===============================================================================================================================================
#=============Helper function for mapping HDF5 structure to text===========================================================
#===============================================================================================================================================
def map_structure_to_text(file_path, output_txt_path):
    """Writes the entire internal structure of an HDF5 file to a text file."""

    with h5py.File(file_path, 'r') as f, open(output_txt_path, 'w') as out_file:
        out_file.write(f"--- Structure of {file_path} ---\n\n")

        # This function will be called for every single item in the file
        def print_item(name, obj):
            indent = "  " * name.count('/')
            if isinstance(obj, h5py.Group):
                out_file.write(f"{indent}Group: {name}/\n")
            elif isinstance(obj, h5py.Dataset):
                out_file.write(f"{indent}Dataset: {name} | Shape: {obj.shape} | Type: {obj.dtype}\n")

        # visititems recursively walks through the entire HDF5 file
        f.visititems(print_item)
        print(f"File structure successfully saved to {output_txt_path}")


#===============================================================================================================================================
#<o> <o> <o> <o> <o> <o> <o> <o> <o> <o> <o> <o> <o> <o> <o> <o> <o> <o> <o> <o> <o> <o> <o> <o> <o> <o> <o> <o> <o> <o> <o> <o> <o> <o> <o> <o>
#===============================================================================================================================================

if __name__ == '__main__':

	path= r"E:\AUG2025\P23"
	fn = "41_He1kG430G_5450A_P23_K20_2025-08-14.hdf5"
	ifn = os.path.join(path, fn)
	print_info(ifn)
