"""Generic digital-signal-processing helpers (filters, STFT, envelopes)."""

from data_analysis.signal.core import (
    downsample_stride,
    downsample_blockmean,
    downsample_decimate,
    DOWNSAMPLE_METHODS,
    analyze_downsample_options,
    butter_bandpass,
    calculate_stft,
    clip_time_window,
    finite_row_mask,
    line_average,
    amplitude_spectrum,
    avg_amplitude_spectrum,
    cross_correlation,
    coherence_spectrum,
    cross_phase_spectrum,
    avg_cross_spectrum,
    band_cross_spectrum,
    peak_cross_spectrum,
)

__all__ = [
    "downsample_stride",
    "downsample_blockmean",
    "downsample_decimate",
    "DOWNSAMPLE_METHODS",
    "analyze_downsample_options",
    "butter_bandpass",
    "calculate_stft",
    "clip_time_window",
    "finite_row_mask",
    "line_average",
    "amplitude_spectrum",
    "avg_amplitude_spectrum",
    "cross_correlation",
    "coherence_spectrum",
    "cross_phase_spectrum",
    "avg_cross_spectrum",
    "band_cross_spectrum",
    "peak_cross_spectrum",
]
